[package]
name    = "svc-storage"
<<<<<<< HEAD
<<<<<<< HEAD
version = "0.0.0"
edition = "2021"        # Allowed values are 2015, 2018, 2021
=======
version = "0.4.19-develop.0"
=======
version = "0.4.22-develop.0"
>>>>>>> 2f9c581 (chore(ci): update files for release<br/><br/>[skip ci])
edition = "2021"             # Allowed values are 2015, 2018, 2021
>>>>>>> ab4354a (chore(ci): update files for release\n\n[skip ci])
# Rust Editions: https://doc.rust-lang.org/edition-guide/index.html

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cargo-husky = "1"
chrono      = { version = "0.4.22", features = ["serde"] }
hyper       = "0.14.20"
prost       = "0.11.0"
prost-build = "0.11.1"
prost-types = "0.11.1"
serde       = "1.0.144"
serde_json  = "1.0.85"
tokio       = { version = "1.20.1", features = ["full"] }
tokio-util  = "0.7.3"
tonic       = "0.8.2"

[build-dependencies]
tonic-build = "0.8"
