[package]
edition = "2021"
name    = "svc-storage-client-grpc"
<<<<<<< HEAD
<<<<<<< HEAD
version = "0.0.0"
=======
version = "0.4.19-develop.0"
=======
version = "0.4.22-develop.0"
>>>>>>> 2f9c581 (chore(ci): update files for release<br/><br/>[skip ci])

>>>>>>> ab4354a (chore(ci): update files for release\n\n[skip ci])
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
prost       = "0.11.0"
prost-types = "0.11.1"
tonic       = "0.8.1"

[dev-dependencies]
tokio = { version = "1.0", features = ["macros", "rt-multi-thread"] }

[[example]]
name = "grpc"
