[package]
edition = "2021"
name    = "svc-storage-client-grpc"
version = "0.4.14-develop.1"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
prost       = "0.11.0"
prost-types = "0.11.1"
tonic       = "0.8.1"

[dev-dependencies]
tokio = { version = "1.0", features = ["macros", "rt-multi-thread"] }

[[example]]
name = "grpc"
